name: Daily Culinary Fact Generator

on:
  schedule:
    # Runs the action every day at 10:00 AM UTC
    - cron: '0 10 * * *' 
  workflow_dispatch: # Allows you to run it manually

jobs:
  generate_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Required to allow the workflow to commit back to the repo
          token: ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests # Installs the library needed for API calls

      - name: Generate the new fact
        # Execute your Python script, passing the AI_API_KEY secret
        run: python generate_fact.py
        env:
          AI_API_KEY: ${{ secrets.AI_API_KEY }}

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '🤖 Automated: New daily culinary fact generated.'
          # This will commit the updated 'current_fact.txt' file
